const seed=[
['The St. Regis Le Morne Resort','Le Morne','Southwest','https://www.marriott.com/en-us/hotels/mruxm-the-st-regis-le-morne-resort-mauritius/overview/',['Beach','Spa','Pool','Luxury']],
['LUX* Le Morne','Le Morne','Southwest','https://www.luxresorts.com/en/mauritius/hotel/luxlemorne',['Beach','Spa','Pool','Sunset']],
['Constance Prince Maurice','Poste de Flacq','East','https://www.constancehotels.com/en/hotels-resorts/mauritius/prince-maurice/',['Beach','Spa','Pool','Luxury']],
['Four Seasons Resort Mauritius at Anahita','Beau Champ','East','https://www.fourseasons.com/mauritius/',['Villas','Golf','Beach','Spa']],
['Shangri-La Le Touessrok','Trou d’Eau Douce','East','https://www.shangri-la.com/mauritius/shangrila/',['Beach','Golf','Spa','Luxury']],
['Constance Belle Mare Plage','Belle Mare','East','https://www.constancehotels.com/en/hotels-resorts/mauritius/belle-mare-plage/',['Beach','Golf','Pool','Spa']],
['LUX* Belle Mare','Belle Mare','East','https://www.luxresorts.com/en/mauritius/hotel/luxbellemare',['Beach','Design','Pool','Spa']],
['The Oberoi Beach Resort, Mauritius','Turtle Bay','Northwest','https://www.oberoihotels.com/hotels-in-mauritius/',['Beach','Quiet','Spa','Luxury']],
['Royal Palm Beachcomber Luxury','Grand Baie','North','https://www.beachcomber-hotels.com/en/hotel/royal-palm-beachcomber-luxury',['Beach','Luxury','Spa','Pool']],
['LUX* Grand Baie','Grand Baie','North','https://www.luxresorts.com/en/mauritius/hotel/luxgrandbaie',['Design','Rooftop','Beach','Spa']],
['Paradise Cove Boutique Hotel','Anse La Raie','North','https://www.paradisecovehotel.com/',['Boutique','Adults','Beach','Romantic']],
['SALT of Palmar','Palmar','East','https://www.saltresorts.com/en/mauritius/hotel/saltofpalmar',['Boutique','Adults','Design','Beach']],
['Sugar Beach Mauritius','Flic-en-Flac','West','https://www.sugarbeachresort.com/',['Beach','Golf','Spa','Sunset']],
['La Pirogue Mauritius','Flic-en-Flac','West','https://www.lapirogue.com/',['Beach','Pool','Spa','Relaxed']],
['Shanti Maurice Resort & Spa','Saint Felix','South','https://www.shantimaurice.com/',['Wellness','Beach','Quiet','Spa']]
];
let hotels=JSON.parse(localStorage.getItem('vacationHotels')||'null')||seed.map((x,i)=>({id:i+1,name:x[0],place:x[1],region:x[2],url:x[3],features:x[4],vote:'maybe'}));let filter='all';let ranking=false;const grid=document.querySelector('#hotelGrid');
function save(){localStorage.setItem('vacationHotels',JSON.stringify(hotels))}function render(){let shown=filter==='all'?hotels:hotels.filter(h=>h.vote===filter);grid.innerHTML=shown.map(h=>`<article class="hotel" draggable="${ranking}" data-id="${h.id}"><div class="image"><span class="rank">#${hotels.findIndex(x=>x.id===h.id)+1}</span><span class="region">${h.region}</span></div><div class="body"><h3>${h.name}</h3><div class="meta">${h.place} · Mauritius</div><div class="chips">${h.features.map(f=>`<span class="chip">${f}</span>`).join('')}</div><div class="voteTitle">Deine Auswahl</div><div class="votes">${[['yes','❤️'],['maybe','🤔'],['no','👎']].map(v=>`<button class="vote ${h.vote===v[0]?'selected':''}" data-vote="${v[0]}" data-id="${h.id}">${v[1]}</button>`).join('')}</div><div class="footer"><a href="${h.url}" target="_blank" rel="noopener">Website ↗</a><span class="handle">${ranking?'☰ Ziehen':'Ranking #'+(hotels.findIndex(x=>x.id===h.id)+1)}</span></div></div></article>`).join('');document.querySelector('#count').textContent=hotels.length;document.querySelector('#liked').textContent=hotels.filter(h=>h.vote==='yes').length;bindDrag()}
document.addEventListener('click',e=>{let b=e.target.closest('[data-vote]');if(b){hotels.find(h=>h.id==b.dataset.id).vote=b.dataset.vote;save();render()}let t=e.target.closest('.tab');if(t){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');filter=t.dataset.filter;render()}});
function bindDrag(){if(!ranking)return;let dragged;document.querySelectorAll('.hotel').forEach(c=>{c.addEventListener('dragstart',()=>{dragged=c;c.classList.add('dragging')});c.addEventListener('dragend',()=>c.classList.remove('dragging'));c.addEventListener('dragover',e=>e.preventDefault());c.addEventListener('drop',e=>{e.preventDefault();if(!dragged||dragged===c)return;let a=hotels.findIndex(h=>h.id==dragged.dataset.id),b=hotels.findIndex(h=>h.id==c.dataset.id);let [m]=hotels.splice(a,1);hotels.splice(b,0,m);save();render()})})}
addBtn.onclick=()=>addDialog.showModal();addForm.onsubmit=e=>{if(e.submitter?.value==='cancel')return;let url=hotelUrl.value;let host=new URL(url).hostname.replace(/^www\./,'');hotels.push({id:Date.now(),name:host,place:'Noch zu analysieren',region:'Neu',url,features:['Imported'],vote:'maybe'});save();hotelUrl.value='';render()};rankBtn.onclick=()=>{ranking=!ranking;rankBtn.textContent=ranking?'✓ Ranking fertig':'↕ Ranking';render()};compareBtn.onclick=()=>{let shortlist=hotels.filter(h=>h.vote!=='no').slice(0,6);compareContent.innerHTML=`<table class="compareTable"><tr><th>Hotel</th><th>Region</th><th>Vote</th><th>Features</th></tr>${shortlist.map(h=>`<tr><td>${h.name}</td><td>${h.region}</td><td>${h.vote==='yes'?'❤️':'🤔'}</td><td>${h.features.join(', ')}</td></tr>`).join('')}</table>`;compareDialog.showModal()};render();